# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa5098cfa2f52d841eaa865234492ae52a270354676aa4933fdbab0c6a85b762291b4ba6cba3f9cf8f7ceaf465f8b2c07321784f15b7275044a9120753e0f16

test:
  secret_key_base: e2716981563ef5f162f43b62acd3e567e7def9f7ce06c5ab4780fabb1eaaeea9fa42a2fe8d586490461c0f7eb62a20ac67f025e82973873dc1ec4ff3de1db119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
